name: Workflow stats

on:
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPOSITORY: vergiLgood1/vergiLgood1
          SHOW_TITLE: true
          TIME_RANGE: all_time
          LANG_COUNT: 6
          SHOW_TIME: true
          SHOW_TOTAL: true
          BLOCKS: ▰▰▰▰▰▱▱▱▱▱▱
          STOP_AT_OTHER: true
          SHOW_MASKED_TIME: false
